// Code generated by mockery v2.30.1. DO NOT EDIT.

package repomock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HealthRepoInterface is an autogenerated mock type for the HealthRepoInterface type
type HealthRepoInterface struct {
	mock.Mock
}

// PingPostgres provides a mock function with given fields: ctx
func (_m *HealthRepoInterface) PingPostgres(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewHealthRepoInterface creates a new instance of HealthRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthRepoInterface {
	mock := &HealthRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
