FROM golang:1.20-rc-bullseye

WORKDIR /migrate

RUN curl -sSf https://atlasgo.sh -o atlasgo.sh && chmod +x atlasgo.sh && ./atlasgo.sh -y
RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

COPY justfile ./
COPY migrations ./migrations

CMD [ "just", "migrate-apply" ]